// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: squareroot/sqarerootPB/sqaretroot.proto

package sqarerootPB

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqaureRootRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SqaureRootRequest) Reset() {
	*x = SqaureRootRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqaureRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqaureRootRequest) ProtoMessage() {}

func (x *SqaureRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqaureRootRequest.ProtoReflect.Descriptor instead.
func (*SqaureRootRequest) Descriptor() ([]byte, []int) {
	return file_squareroot_sqarerootPB_sqaretroot_proto_rawDescGZIP(), []int{0}
}

func (x *SqaureRootRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type SquareRootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberRoot float64 `protobuf:"fixed64,1,opt,name=numberRoot,proto3" json:"numberRoot,omitempty"`
}

func (x *SquareRootResponse) Reset() {
	*x = SquareRootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareRootResponse) ProtoMessage() {}

func (x *SquareRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareRootResponse.ProtoReflect.Descriptor instead.
func (*SquareRootResponse) Descriptor() ([]byte, []int) {
	return file_squareroot_sqarerootPB_sqaretroot_proto_rawDescGZIP(), []int{1}
}

func (x *SquareRootResponse) GetNumberRoot() float64 {
	if x != nil {
		return x.NumberRoot
	}
	return 0
}

var File_squareroot_sqarerootPB_sqaretroot_proto protoreflect.FileDescriptor

var file_squareroot_sqarerootPB_sqaretroot_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x73, 0x71, 0x61,
	0x72, 0x65, 0x72, 0x6f, 0x6f, 0x74, 0x50, 0x42, 0x2f, 0x73, 0x71, 0x61, 0x72, 0x65, 0x74, 0x72,
	0x6f, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x74, 0x72, 0x6f, 0x6f, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x71, 0x61, 0x75, 0x72, 0x65,
	0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0x34, 0x0a, 0x12, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x74, 0x32, 0x64, 0x0a, 0x11, 0x53, 0x71, 0x75,
	0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x0a, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x1e, 0x2e, 0x73,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x74, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x53, 0x71, 0x61, 0x75, 0x72,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73,
	0x71, 0x75, 0x61, 0x72, 0x65, 0x74, 0x72, 0x6f, 0x6f, 0x74, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x19, 0x5a, 0x17, 0x2e, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x73,
	0x71, 0x61, 0x72, 0x65, 0x72, 0x6f, 0x6f, 0x74, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_squareroot_sqarerootPB_sqaretroot_proto_rawDescOnce sync.Once
	file_squareroot_sqarerootPB_sqaretroot_proto_rawDescData = file_squareroot_sqarerootPB_sqaretroot_proto_rawDesc
)

func file_squareroot_sqarerootPB_sqaretroot_proto_rawDescGZIP() []byte {
	file_squareroot_sqarerootPB_sqaretroot_proto_rawDescOnce.Do(func() {
		file_squareroot_sqarerootPB_sqaretroot_proto_rawDescData = protoimpl.X.CompressGZIP(file_squareroot_sqarerootPB_sqaretroot_proto_rawDescData)
	})
	return file_squareroot_sqarerootPB_sqaretroot_proto_rawDescData
}

var file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_squareroot_sqarerootPB_sqaretroot_proto_goTypes = []interface{}{
	(*SqaureRootRequest)(nil),  // 0: squaretroot.SqaureRootRequest
	(*SquareRootResponse)(nil), // 1: squaretroot.SquareRootResponse
}
var file_squareroot_sqarerootPB_sqaretroot_proto_depIdxs = []int32{
	0, // 0: squaretroot.SquareRootService.SquareRoot:input_type -> squaretroot.SqaureRootRequest
	1, // 1: squaretroot.SquareRootService.SquareRoot:output_type -> squaretroot.SquareRootResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_squareroot_sqarerootPB_sqaretroot_proto_init() }
func file_squareroot_sqarerootPB_sqaretroot_proto_init() {
	if File_squareroot_sqarerootPB_sqaretroot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqaureRootRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareRootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_squareroot_sqarerootPB_sqaretroot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_squareroot_sqarerootPB_sqaretroot_proto_goTypes,
		DependencyIndexes: file_squareroot_sqarerootPB_sqaretroot_proto_depIdxs,
		MessageInfos:      file_squareroot_sqarerootPB_sqaretroot_proto_msgTypes,
	}.Build()
	File_squareroot_sqarerootPB_sqaretroot_proto = out.File
	file_squareroot_sqarerootPB_sqaretroot_proto_rawDesc = nil
	file_squareroot_sqarerootPB_sqaretroot_proto_goTypes = nil
	file_squareroot_sqarerootPB_sqaretroot_proto_depIdxs = nil
}
