// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: greet/greetpb/sum.proto

package greetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoSum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int32 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int32 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *DoSum) Reset() {
	*x = DoSum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_sum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSum) ProtoMessage() {}

func (x *DoSum) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_sum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSum.ProtoReflect.Descriptor instead.
func (*DoSum) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_sum_proto_rawDescGZIP(), []int{0}
}

func (x *DoSum) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *DoSum) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type DoSumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dosum *DoSum `protobuf:"bytes,1,opt,name=dosum,proto3" json:"dosum,omitempty"`
}

func (x *DoSumRequest) Reset() {
	*x = DoSumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_sum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoSumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSumRequest) ProtoMessage() {}

func (x *DoSumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_sum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSumRequest.ProtoReflect.Descriptor instead.
func (*DoSumRequest) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_sum_proto_rawDescGZIP(), []int{1}
}

func (x *DoSumRequest) GetDosum() *DoSum {
	if x != nil {
		return x.Dosum
	}
	return nil
}

type DoSumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sum int32 `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (x *DoSumResponse) Reset() {
	*x = DoSumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_greet_greetpb_sum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoSumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoSumResponse) ProtoMessage() {}

func (x *DoSumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_greet_greetpb_sum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoSumResponse.ProtoReflect.Descriptor instead.
func (*DoSumResponse) Descriptor() ([]byte, []int) {
	return file_greet_greetpb_sum_proto_rawDescGZIP(), []int{2}
}

func (x *DoSumResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

var File_greet_greetpb_sum_proto protoreflect.FileDescriptor

var file_greet_greetpb_sum_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70, 0x62, 0x2f,
	0x73, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x22, 0x23, 0x0a, 0x05, 0x44, 0x6f, 0x53, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x62, 0x22, 0x32, 0x0a, 0x0c, 0x64, 0x6f, 0x53, 0x75, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x64, 0x6f, 0x73, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x44, 0x6f, 0x53,
	0x75, 0x6d, 0x52, 0x05, 0x64, 0x6f, 0x73, 0x75, 0x6d, 0x22, 0x21, 0x0a, 0x0d, 0x64, 0x6f, 0x53,
	0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x75, 0x6d, 0x32, 0x40, 0x0a, 0x0c,
	0x64, 0x6f, 0x53, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x03,
	0x53, 0x75, 0x6d, 0x12, 0x13, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2e, 0x64, 0x6f, 0x53, 0x75,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x2e, 0x64, 0x6f, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11,
	0x5a, 0x0f, 0x2e, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_greet_greetpb_sum_proto_rawDescOnce sync.Once
	file_greet_greetpb_sum_proto_rawDescData = file_greet_greetpb_sum_proto_rawDesc
)

func file_greet_greetpb_sum_proto_rawDescGZIP() []byte {
	file_greet_greetpb_sum_proto_rawDescOnce.Do(func() {
		file_greet_greetpb_sum_proto_rawDescData = protoimpl.X.CompressGZIP(file_greet_greetpb_sum_proto_rawDescData)
	})
	return file_greet_greetpb_sum_proto_rawDescData
}

var file_greet_greetpb_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_greet_greetpb_sum_proto_goTypes = []interface{}{
	(*DoSum)(nil),         // 0: greet.DoSum
	(*DoSumRequest)(nil),  // 1: greet.doSumRequest
	(*DoSumResponse)(nil), // 2: greet.doSumResponse
}
var file_greet_greetpb_sum_proto_depIdxs = []int32{
	0, // 0: greet.doSumRequest.dosum:type_name -> greet.DoSum
	1, // 1: greet.doSumService.Sum:input_type -> greet.doSumRequest
	2, // 2: greet.doSumService.Sum:output_type -> greet.doSumResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_greet_greetpb_sum_proto_init() }
func file_greet_greetpb_sum_proto_init() {
	if File_greet_greetpb_sum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_greet_greetpb_sum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoSum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greetpb_sum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoSumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_greet_greetpb_sum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoSumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_greet_greetpb_sum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_greet_greetpb_sum_proto_goTypes,
		DependencyIndexes: file_greet_greetpb_sum_proto_depIdxs,
		MessageInfos:      file_greet_greetpb_sum_proto_msgTypes,
	}.Build()
	File_greet_greetpb_sum_proto = out.File
	file_greet_greetpb_sum_proto_rawDesc = nil
	file_greet_greetpb_sum_proto_goTypes = nil
	file_greet_greetpb_sum_proto_depIdxs = nil
}
